version: '3.8'

services:
  space-ai-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped
    
  space-ai-frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://space-ai-backend:8000
    depends_on:
      - space-ai-backend
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
