global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'space-intelligence-app'
    static_configs:
      - targets: ['space-app:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom metrics for space data freshness
  - job_name: 'space-data-metrics'
    static_configs:
      - targets: ['space-app:8501']
    metrics_path: '/_stcore/metrics'
    scrape_interval: 60s