name: Basic Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Basic Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit requests pandas numpy
        
    - name: Test Python Syntax
      run: |
        python -m py_compile main.py || true
        python -m py_compile real_data_sources.py || true
        python -m py_compile core_utils.py || true
        
    - name: Basic Import Test
      run: |
        python -c "import streamlit; print('Streamlit OK')"
        python -c "import requests; print('Requests OK')"
        python -c "import pandas; print('Pandas OK')"
        python -c "import numpy; print('NumPy OK')"
        
    - name: Test Application Structure
      run: |
        ls -la
        test -f main.py || echo "main.py not found"
        test -f requirements.txt || echo "requirements.txt not found"
        test -f Dockerfile || echo "Dockerfile not found"