name: Nightly Data Refresh
on:
  schedule:
    - cron: "20 1 * * *"   # nightly UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ingestion
        run: python scripts/run_all.py
      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          if git diff --cached --quiet; then
            echo "No data changes."
          else
            git commit -m "chore(data): nightly refresh"
            git push
          fi
