[server]
headless = true
fileWatcherType = "none"
runOnSave = false

[theme]
base = "dark"
primaryColor = "#6EE7F9"
backgroundColor = "#0B1120"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[browser]
gatherUsageStats = false
