[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = $PORT

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"